### PR TITLE
this file shouldn't be empty, so I added the missing part

### PR DESCRIPTION
**Pull request by lkthomas**

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
Linked to #5

**Comment by M0NsTeRRR** [comment]
@lkthomas have you seen my review ? waiting for your change to merge the PR

**Comment by lkthomas** [comment]
done, please check

**Comment by M0NsTeRRR** [comment]
@lkthomas you need to add the fix i've writed in the review, uncomment the import you did in the last commit and run pre-commit to fix file formatting.

Or if you prefer you can give me the permission to edit your PR (you have to check a box in your PR to allow mantainer to edit it)

**Comment by lkthomas** [comment]
"Allow edits by maintainers" is always checked

**Pull request merged**
